### ISSUE TITLE
IE11 Issues

### ISSUE THREAD

**Issue by jhildenbiddle** [waruqi/docsify-plugin-carbon#1]
[ChildNode.remove()](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) is not supported by IE11 which docsify v4.x officially supports. The use of this method is breaking https://docsify.js.org/ for IE11 users.

https://github.com/waruqi/docsify-plugin-carbon/blob/31136a791076b0970e551ce4ab89efc8e6c6ab81/index.js#L20

Should be:

```js
window.DocsifyCarbon.scriptEl.parentNode.removeChild(window.DocsifyCarbon.scriptEl)
```

I would have created a PR, but you don't have a build in place to generate `index.min.js`.

Thanks!

**Comment by waruqi** [comment]
you can open a pr to modify index.js and index.min.js

**Comment by jhildenbiddle** [comment]
@waruqi Yes. I am aware.

Since your repo does not include a build script or instructions on how others should build/minify, my hope was that you would make the one line change, minify as you have previously, and then publish a point release.

I am happy to add some basic instructions for minification in addition to the fix. Just let me know if you have a preferred library and settings.

**Comment by waruqi** [comment]
I use an online js compression tool, but I forgot which one I used, sorry.

You can choose a build/minify tool you recommend to generate it. As long as it can run normally.
